// Header mega-menus.
// Services: segmented tabs → columns of services → full-width banner.
// "Our Work" and "Insights" use the split layout: description + banner on the left, image on the right.
// Edit the MENUS data below to change any label, link or copy.
(() => {
  // Content follows the header design (04–06 · Header — Desktop / Tablet / Mobile).
  // `h` = link: items that exist on squarezix.com link there; the rest go to contact.
  const LIVE = 'https://squarezix.com';
  const CONTACT = `${LIVE}/contact-us/`;
  const MENUS = {
    services: {
      layout: 'cols',
      // Generated by scripts/build_service_pages.py from the service pages — edit there, not here.
      // <services:auto>
      tabs: [
        {
          "label": "Branding & Design",
          "page": "branding.html",
          "cols": [
            {
              "title": "Branding",
              "page": "branding.html",
              "items": [
                {
                  "t": "Brand Strategy & Positioning",
                  "h": "brand-strategy-and-positioning.html"
                },
                {
                  "t": "Visual Identity Design",
                  "h": "visual-identity-design.html"
                },
                {
                  "t": "Brand Audit & Rebranding",
                  "h": "brand-audit-and-rebranding.html"
                },
                {
                  "t": "Brand Experience & Touchpoints",
                  "h": "brand-experience-and-touchpoints.html"
                },
                {
                  "t": "Brand Collateral & Print Design",
                  "h": "brand-collateral-and-print-design.html"
                }
              ]
            },
            {
              "title": "Design",
              "page": "design.html",
              "items": [
                {
                  "t": "Web & App Design",
                  "h": "web-and-app-design.html"
                },
                {
                  "t": "Revamp Website",
                  "h": "revamp-website.html"
                },
                {
                  "t": "Ecommerce Website Design",
                  "h": "ecommerce-website-design.html"
                },
                {
                  "t": "Social Media Design",
                  "h": "social-media-design.html"
                },
                {
                  "t": "Email Marketing Testing & Design",
                  "h": "email-marketing-testing-and-design.html"
                }
              ]
            }
          ]
        },
        {
          "label": "Digital Marketing",
          "page": null,
          "cols": [
            {
              "title": "Social Media",
              "page": "social-media-marketing.html",
              "items": [
                {
                  "t": "Community Management",
                  "h": "community-management.html"
                },
                {
                  "t": "Content Creation Services",
                  "h": "content-creation-services.html"
                },
                {
                  "t": "Advertising & Media Services",
                  "h": "advertising-and-media-services.html"
                },
                {
                  "t": "Social Media Event Management",
                  "h": "social-media-event-management.html"
                }
              ]
            },
            {
              "title": "Content Marketing",
              "page": "content-marketing.html",
              "items": [
                {
                  "t": "Website Copywriting",
                  "h": "website-copywriting.html"
                },
                {
                  "t": "Multimedia Content Assets",
                  "h": "multimedia-content-assets.html"
                },
                {
                  "t": "Digital PR",
                  "h": "digital-pr.html"
                }
              ]
            },
            {
              "title": "Paid Marketing",
              "page": "paid-marketing.html",
              "items": [
                {
                  "t": "Search & Display Advertising",
                  "h": "search-and-display-advertising.html",
                  "d": "Google Search · Google Display · Bing Ads"
                },
                {
                  "t": "Shopping & Marketplace Advertising",
                  "h": "shopping-and-marketplace-advertising.html",
                  "d": "Google Shopping · Shopping Feed Optimization · Amazon PPC"
                },
                {
                  "t": "Social & App Advertising",
                  "h": "social-and-app-advertising.html",
                  "d": "Social Ads · App Install Ads"
                },
                {
                  "t": "Retargeting & Remarketing",
                  "h": "retargeting-and-remarketing.html",
                  "d": "Retargeting · Remarketing Campaigns"
                }
              ]
            }
          ]
        },
        {
          "label": "AI Search & SEO",
          "page": null,
          "cols": [
            {
              "title": "AI & Search Visibility",
              "page": "seo-ai-visibility.html",
              "items": [
                {
                  "t": "Search Engine Optimization",
                  "h": "search-engine-optimization.html"
                },
                {
                  "t": "Local SEO",
                  "h": "local-seo.html"
                },
                {
                  "t": "Enterprise SEO",
                  "h": "enterprise-seo.html"
                },
                {
                  "t": "Ecommerce SEO",
                  "h": "ecommerce-seo.html"
                },
                {
                  "t": "AI & LLM SEO",
                  "h": "ai-and-llm-seo.html"
                },
                {
                  "t": "Generative AI Research and Analysis",
                  "h": "generative-ai-research-and-analysis.html"
                },
                {
                  "t": "Semantic Keywords Research",
                  "h": "semantic-keywords-research.html"
                },
                {
                  "t": "AI-Optimized Content",
                  "h": "ai-optimized-content.html"
                },
                {
                  "t": "Community Engagement Optimization",
                  "h": "community-engagement-optimization.html"
                },
                {
                  "t": "Brand Visibility and Authority",
                  "h": "brand-visibility-and-authority.html"
                },
                {
                  "t": "AI-Friendly Structured Data",
                  "h": "ai-friendly-structured-data.html"
                }
              ]
            }
          ]
        }
      ],
      // </services:auto>
      banner: { kicker: 'Free audit', title: 'Is your brand getting noticed?', cta: 'Get a free brand & marketing audit', href: CONTACT },
    },
    dev: {
      layout: 'cols',
      // Generated by scripts/build_service_pages.py — edit there, not here.
      // <dev:auto>
      tabs: [
        {
          "label": "Website Development",
          "page": "website-development.html",
          "cols": [
            {
              "title": "Website Development",
              "page": "website-development.html",
              "items": [
                {
                  "t": "WordPress Development",
                  "h": "wordpress-development.html"
                },
                {
                  "t": "Ecommerce Website Development",
                  "h": "ecommerce-website-development.html"
                },
                {
                  "t": "React JS Development",
                  "h": "react-js-development.html"
                },
                {
                  "t": "Next.js Development",
                  "h": "next-js-development.html"
                },
                {
                  "t": "Full-Stack Web Development",
                  "h": "full-stack-web-development.html"
                },
                {
                  "t": "Custom CMS Development",
                  "h": "custom-cms-development.html"
                },
                {
                  "t": "Headless CMS Development",
                  "h": "headless-cms-development.html"
                },
                {
                  "t": "Concrete CMS Development",
                  "h": "concrete-cms-development.html"
                },
                {
                  "t": "Vue.js Development",
                  "h": "vue-js-development.html"
                }
              ]
            }
          ]
        },
        {
          "label": "Website Maintenance",
          "page": "website-maintenance.html",
          "cols": [
            {
              "title": "Website Maintenance",
              "page": "website-maintenance.html",
              "items": [
                {
                  "t": "24/7 Uptime Monitoring",
                  "h": "24-7-uptime-monitoring.html"
                },
                {
                  "t": "Premium Hosting Performance",
                  "h": "premium-hosting-performance.html"
                },
                {
                  "t": "Weekly & Monthly Backups",
                  "h": "weekly-and-monthly-backups.html"
                },
                {
                  "t": "Website & Traffic Analytics",
                  "h": "website-and-traffic-analytics.html"
                },
                {
                  "t": "Site Security & Certification",
                  "h": "site-security-and-certification.html"
                },
                {
                  "t": "Content Updates & On-Demand Edits",
                  "h": "content-updates-and-on-demand-edits.html"
                },
                {
                  "t": "Speed & Performance Optimization",
                  "h": "speed-and-performance-optimization.html"
                }
              ]
            }
          ]
        }
      ],
      // </dev:auto>
      banner: { kicker: 'Free audit', title: 'Is your website holding you back?', cta: 'Get a free website audit', href: CONTACT },
    },
    work: {
      layout: 'split',
      tabs: [
        { label: 'Portfolio', title: 'Portfolio', img: 'assets/work/project-2.png',
          d: 'Websites, brands and campaigns we have designed, built and launched for clients across the GCC and beyond.',
          banner: { title: 'See our work', cta: 'View portfolio', href: 'index.html#work' } },
        { label: 'Case Studies', title: 'Case Studies', img: 'assets/work/project-3.png',
          d: 'The brief, what we did and the results — a closer look at projects from first workshop to launch and growth.',
          banner: { title: 'Proof, not promises', cta: 'Read case studies', href: `${LIVE}/case-study/` } },
      ],
    },
    insights: {
      layout: 'split',
      tabs: [
        { label: 'Blogs', title: 'Blogs', img: 'assets/work/project-3.png',
          d: 'Field notes on design, SEO and AI search from the team shipping it every week — practical, no fluff.',
          banner: { title: 'Read the latest articles', cta: 'Visit the blog', href: `${LIVE}/blogs/` } },
        { label: 'Our Culture', title: 'Our Culture', img: 'assets/footer/sz-stage.jpg',
          d: 'Our story, mission, vision and awards — how a Dubai studio grew into a partner for brands across the GCC and Asia.',
          banner: { title: 'Life at Squarezix', cta: 'Meet the team', href: 'about-us.html#culture' } },
        { label: 'Career', title: 'Career', img: 'assets/work/project-1.png',
          d: 'Designers, developers and strategists who like hard problems. Hybrid in Dubai, remote-friendly across the region.',
          banner: { title: "We're hiring", cta: 'See open roles', href: `${LIVE}/careers/` } },
        { label: 'About Us', title: 'About Us', img: 'assets/footer/sz-stage.jpg',
          d: 'Who we are, how we work and the team behind 1,000+ websites — a Dubai studio built around strategy, design and growth.',
          banner: { title: 'Get to know Squarezix', cta: 'About us', href: 'about-us.html' } },
      ],
    },
  };

  const ARROW = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 17 17 7M8 7h9v9"/></svg>';
  const CHEVRON = '<svg class="nav-chev" viewBox="0 0 24 24" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>';
  const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');

  const banner = (b) => `
    <a class="mm-banner" href="${b.href}">
      <span class="mm-banner-copy">
        ${b.kicker ? `<span class="mm-banner-kicker">${esc(b.kicker)}</span>` : ''}
        <span class="mm-banner-title">${esc(b.title)}</span>
      </span>
      <span class="mm-banner-cta">${esc(b.cta)} ${ARROW}</span>
    </a>`;

  // Services: each tab holds one or more columns; a column = heading link + its services
  const colsPane = (tab) => `
    <div class="mm-cols${tab.cols.length === 1 ? ' mm-cols--one' : ''}" style="--c:${tab.cols.length}">
      ${tab.cols.map((c) => `
        <div class="mm-col">
          <a class="mm-col-head" href="${c.page}">${esc(c.title)} ${ARROW}</a>
          <ul class="mm-links">
            ${c.items.map((it) => it.d
              ? `<li><a class="mm-link-rich" href="${it.h}"><b>${esc(it.t)}</b><span>${esc(it.d)}</span></a></li>`
              : `<li><a href="${it.h}">${esc(it.t)}</a></li>`).join('')}
          </ul>
        </div>`).join('')}
    </div>`;

  const splitPane = (tab) => `
    <div class="mm-split">
      <div class="mm-split-copy">
        <h3>${esc(tab.title)}</h3>
        <p>${esc(tab.d)}</p>
        ${banner(tab.banner)}
      </div>
      <div class="mm-split-media"><img src="${tab.img}" alt="" loading="lazy" /></div>
    </div>`;

  const desktop = matchMedia('(min-width: 1081px)');
  // --- Build a panel for every [data-menu] trigger ---
  const header = document.querySelector('.site-header');
  const items = [...document.querySelectorAll('.nav-item[data-menu]')];
  items.forEach((item) => {
    const key = item.dataset.menu;
    const data = MENUS[key];
    const trigger = item.querySelector('.nav-trigger');
    const panelId = `mm-${key}`;
    trigger.insertAdjacentHTML('beforeend', CHEVRON);
    trigger.setAttribute('aria-expanded', 'false');
    trigger.setAttribute('aria-controls', panelId);

    const panel = document.createElement('div');
    panel.className = `mm-panel${data.layout ? ` mm-panel--${data.layout}` : ''}`;
    panel.id = panelId;
    panel.innerHTML = `
      <div class="mm-tabs" role="tablist" aria-label="${esc(trigger.textContent.trim())}" style="--n:${data.tabs.length}">
        <span class="mm-tab-thumb" aria-hidden="true"></span>
        ${data.tabs.map((t, i) => `<button class="mm-tab" type="button" role="tab" id="${panelId}-t${i}"
            aria-controls="${panelId}-p${i}" aria-selected="${i === 0}" tabindex="${i === 0 ? 0 : -1}">${esc(t.label)}</button>`).join('')}
      </div>
      ${data.tabs.map((t, i) => `<div class="mm-pane" role="tabpanel" id="${panelId}-p${i}" aria-labelledby="${panelId}-t${i}"${i === 0 ? '' : ' hidden'}>
          ${data.layout === 'split' ? splitPane(t) : data.layout === 'cols' ? colsPane(t) : gridPane(t)}
        </div>`).join('')}
      ${data.banner ? banner(data.banner) : ''}`;
    item.appendChild(panel);

    // --- Tabs: click, hover (short intent delay) and arrow keys ---
    const tabs = [...panel.querySelectorAll('.mm-tab')];
    const panes = [...panel.querySelectorAll('.mm-pane')];
    const tablist = panel.querySelector('.mm-tabs');
    const select = (i, focus) => {
      tabs.forEach((t, j) => {
        t.setAttribute('aria-selected', j === i);
        t.tabIndex = j === i ? 0 : -1;
        panes[j].hidden = j !== i;
      });
      tablist.style.setProperty('--i', i);
      if (focus) tabs[i].focus();
    };
    let hoverTimer;
    tabs.forEach((t, i) => {
      t.addEventListener('click', (e) => {
        // Mouse (any width): hover already shows the tab's services, so a click opens its page.
        // Touch and keyboard: the first press selects the tab, a press on the selected tab opens it.
        const page = data.tabs[i].page;
        const selected = t.getAttribute('aria-selected') === 'true';
        if (page && (selected || e.pointerType === 'mouse')) { location.href = page; return; }
        select(i);
      });
      t.addEventListener('pointerenter', (e) => {
        if (e.pointerType !== 'mouse') return;
        clearTimeout(hoverTimer);
        hoverTimer = setTimeout(() => select(i), 120);
      });
      t.addEventListener('pointerleave', () => clearTimeout(hoverTimer));
      t.addEventListener('keydown', (e) => {
        const n = tabs.length;
        if (e.key === 'ArrowRight') { e.preventDefault(); select((i + 1) % n, true); }
        if (e.key === 'ArrowLeft') { e.preventDefault(); select((i - 1 + n) % n, true); }
      });
    });
  });

  // --- Open / close ---
  let openItem = null;
  let closeTimer;

  const open = (item) => {
    clearTimeout(closeTimer);
    if (openItem === item) return;
    if (openItem) close(openItem, false);
    openItem = item;
    item.classList.add('is-open');
    item.querySelector('.nav-trigger').setAttribute('aria-expanded', 'true');
    header.classList.add('mm-active');
  };
  function close(item, clearHeader = true) {
    if (!item) return;
    item.classList.remove('is-open');
    item.querySelector('.nav-trigger').setAttribute('aria-expanded', 'false');
    if (openItem === item) openItem = null;
    if (clearHeader && !openItem) header.classList.remove('mm-active');
  }

  items.forEach((item) => {
    const trigger = item.querySelector('.nav-trigger');
    trigger.addEventListener('click', (e) => {
      // Desktop mouse: hover already opened it, so a click keeps it open. Touch and keyboard toggle.
      if (desktop.matches && e.pointerType === 'mouse') { open(item); return; }
      item.classList.contains('is-open') ? close(item) : open(item);
    });
    // Desktop hover with a grace period so moving diagonally into the panel doesn't close it
    item.addEventListener('pointerenter', (e) => { if (desktop.matches && e.pointerType === 'mouse') open(item); });
    item.addEventListener('pointerleave', (e) => {
      if (!desktop.matches || e.pointerType !== 'mouse') return;
      closeTimer = setTimeout(() => close(item), 220);
    });
    trigger.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowDown') { e.preventDefault(); open(item); item.querySelector('.mm-tab[aria-selected="true"]').focus(); }
    });
    // Closing when focus leaves the menu (keyboard users tabbing past it)
    item.addEventListener('focusout', (e) => {
      if (desktop.matches && !item.contains(e.relatedTarget)) close(item);
    });
  });

  document.addEventListener('keydown', (e) => {
    if (e.key !== 'Escape' || !openItem) return;
    const trigger = openItem.querySelector('.nav-trigger');
    close(openItem);
    trigger.focus();
  });
  document.addEventListener('click', (e) => {
    if (openItem && desktop.matches && !openItem.contains(e.target)) close(openItem);
  });
  // Following a link inside a panel closes the menu (and the mobile sheet)
  document.getElementById('main-nav').addEventListener('click', (e) => {
    if (!e.target.closest('.mm-panel a, .nav-link')) return;
    close(openItem);
    header.classList.remove('menu-open');
    document.getElementById('menu-toggle').setAttribute('aria-expanded', 'false');
  });
  desktop.addEventListener('change', () => close(openItem));
})();
