// Extracts evenly spaced JPEG frames from a video using macOS AVFoundation (no ffmpeg needed).
// Usage: swift scripts/extract-frames.swift path/to/video.mp4 [maxFrames=240]
// Output: frames/desktop (<=1600px wide), frames/mobile (<=960px wide), frames/manifest.json
import AVFoundation
import CoreGraphics
import Foundation
import ImageIO
import UniformTypeIdentifiers

let args = CommandLine.arguments
guard args.count >= 2 else {
  print("Usage: swift scripts/extract-frames.swift path/to/video.mp4 [maxFrames]")
  exit(1)
}
let videoURL = URL(fileURLWithPath: args[1])
let maxFrames = args.count > 2 ? Int(args[2]) ?? 240 : 240
let outDir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
  .deletingLastPathComponent().appendingPathComponent("frames")

let asset = AVURLAsset(url: videoURL)
let duration = try await asset.load(.duration).seconds
guard let track = try await asset.loadTracks(withMediaType: .video).first else {
  print("No video track found"); exit(1)
}
let fps = Double(try await track.load(.nominalFrameRate))
let count = min(maxFrames, max(1, Int(duration * min(fps, 30))))
print(String(format: "Video: %.2fs @ %.0ffps -> extracting %d frames", duration, fps, count))

func writeJPEG(_ image: CGImage, to url: URL, quality: Double) {
  let dest = CGImageDestinationCreateWithURL(url as CFURL, UTType.jpeg.identifier as CFString, 1, nil)!
  CGImageDestinationAddImage(dest, image, [kCGImageDestinationLossyCompressionQuality: quality] as CFDictionary)
  CGImageDestinationFinalize(dest)
}

let fm = FileManager.default
try? fm.removeItem(at: outDir)
for (name, width, quality) in [("desktop", 1600.0, 0.65), ("mobile", 960.0, 0.62)] {
  let dir = outDir.appendingPathComponent(name)
  try fm.createDirectory(at: dir, withIntermediateDirectories: true)

  let gen = AVAssetImageGenerator(asset: asset)
  gen.appliesPreferredTrackTransform = true
  gen.requestedTimeToleranceBefore = .zero
  gen.requestedTimeToleranceAfter = .zero
  gen.maximumSize = CGSize(width: width, height: 0)

  for i in 0..<count {
    // Spread frames across the whole video, stopping just short of the end
    let t = count == 1 ? 0 : (duration - 0.05) * Double(i) / Double(count - 1)
    let (image, _) = try await gen.image(at: CMTime(seconds: t, preferredTimescale: 600))
    writeJPEG(image, to: dir.appendingPathComponent(String(format: "%04d.jpg", i + 1)), quality: quality)
  }
  print("  \(name): \(count) frames")
}

let manifest = #"{"count": \#(count), "ext": "jpg"}"#
try manifest.write(to: outDir.appendingPathComponent("manifest.json"), atomically: true, encoding: .utf8)
// Script version so the page also works when opened straight from disk (file:// blocks fetch)
let manifestJS = "// Generated by scripts/extract-frames.swift — loaded as a script (not fetched) so the hero also works from file://\nwindow.HERO_FRAMES = \(manifest);\n"
try manifestJS.write(to: outDir.appendingPathComponent("manifest.js"), atomically: true, encoding: .utf8)
print("Done -> \(outDir.path)")
